# Generated by Django 4.2.7 on 2023-12-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='description',
        ),
    ]
